version: '3'
services:
  mail-box-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_ENV=dev
      - DATABASE_URL=postgres://postgress:postgress@localdb:5432/mailboxdev
      - PGHOST=localdb
      - PGDATABASE=mailboxdev
      - PGUSER=postgres
      - PGPASSWORD=postgres
    depends_on:
      - localdb
      - setup-db

  localdb:
    image: "postgres:10.4-alpine"
    ports:
      - "5432:5432"
  setup-db:
    build:
      context: .
      dockerfile: Dockerfile-local-db-init
    depends_on:
      - localdb
