swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "mail box"
  contact:
    email: "pavlyshyn@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
schemes:
- "http"

securityDefinitions:
  mail-box-basic:
    type: basic
paths:
  /messages:
    get:
      summary: "Get list paginated messages optionally filtered by state"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "getMessages"
      produces:
      - "application/json"
      - "application/json+problem"
      parameters:
        - in: query
          name: q
          description: |
            Status values that need to be considered for filter
          shema:
            type: string
            enum:
            - archived
            - notreaded
            - all
            default: all
        - in: query
          name: continue
          type: string
          description: |
            Pagination token
          pattern: \d+_\d+
        - in: query
          name: limit
          type: integer
          description: |
            Pagination parameter that size op page
          default: 50

      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Message"
        401:
          description: Not autorised request
          schema:
            $ref: "#/definitions/Problem"
        400:
          description: Not valid query
          schema:
            $ref: "#/definitions/Problem"
  /messages/{id}:
    patch:
      summary: "set archived or read fields "
      description: ""
      operationId: "pathMessage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "id"
        type: number
        format: int64
        required: true
      - in: "body"
        name: "body"
        description: "Message status fields read , archived"
        required: true
        schema:
          $ref: "#/definitions/MessageStatus"
      responses:
        400:
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/Problem"
        404:
          description: "Massage not found"
          schema:
            $ref: "#/definitions/Problem"
        405:
          description: "Validation exception"
          schema:
            $ref: "#/definitions/Problem"
definitions:
  MessageStatus:
    type: object
    properties:
      is_read:
        type: boolean
      is_archived:
        type: boolean
  Message:
    allOf:
      - $ref: "#/definitions/MessageStatus"
      - type: object
        properties:
          sender:
            type: string
            pattern: ^\w{2}\s+\w{2}
            description: |
              The Name Sername of the message author
            example: stephen hawking
          subject:
            type: string
            minLength: 3
            maxLength: 100
            description: |
             Short subject
          message:
            type: string
            minLength: 3
            description: |
             The body of the message
          time_sent:
            type: integer
            format : int64
            description: |
              epoch time stamp of message send. All the date is Unix  UTC time.for more https://en.wikipedia.org/wiki/Unix_time
  Problem:
    type: object
    properties:
      type:
        type: string
        format: uri
        description: |
          https://tools.ietf.org/html/rfc7807
          An absolute URI that identifies the problem type.  When dereferenced,
          it SHOULD provide human-readable documentation for the problem type
          (e.g., using HTML).
        default: 'about:blank'
      title:
        type: string
        description: |
          A short, summary of the problem type. Written in english and readable
          for engineers (usually not suited for non technical stakeholders and
          not localized); example: Service Unavailable
      status:
        type: integer
        format: int32
        description: |
          The HTTP status code generated by the origin server for this occurrence
          of the problem.
        minimum: 100
        maximum: 600
        exclusiveMaximum: true
        example: 503
      detail:
        type: string
        description: |
          A human readable explanation specific to this occurrence of the
          problem.
        example: Connection to database timed out
      instance:
        type: string
        format: uri
        description: |
          An absolute URI that identifies the specific occurrence of the problem.
          It may or may not yield further information if dereferenced.
externalDocs:
  description: "Find out more about mailbox api demo"
  url: "https://github.com/Volland/mail-box-demo"